"""empty message

Revision ID: ccba44b2357c
Revises: 
Create Date: 2021-03-08 19:25:23.708343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccba44b2357c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=20000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('phoneNumber', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('biography', sa.String(length=200), nullable=True),
    sa.Column('profilePicture', sa.String(length=255), nullable=True),
    sa.Column('skillLevel', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('username')
    )
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    op.create_table('pantries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=4000), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=2000), nullable=True),
    sa.Column('type', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('instructions', sa.String(length=5000), nullable=True),
    sa.Column('steps', sa.String(length=5000), nullable=True),
    sa.Column('ingredientId', sa.Integer(), nullable=True),
    sa.Column('imagePath', sa.String(length=255), nullable=True),
    sa.Column('videoPath', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pantryItems',
    sa.Column('ingredientId', sa.Integer(), nullable=True),
    sa.Column('pantryId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredientId'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['pantryId'], ['pantries.id'], )
    )
    op.create_table('recipeItems',
    sa.Column('ingredientId', sa.Integer(), nullable=True),
    sa.Column('recipeId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredientId'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipeId'], ['recipes.id'], )
    )
    op.create_table('recipeLikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('recipeId', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipeId'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipeLikes')
    op.drop_table('recipeItems')
    op.drop_table('pantryItems')
    op.drop_table('recipes')
    op.drop_table('pantries')
    op.drop_table('follows')
    op.drop_table('users')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
